services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SecurityBundle\Security\:
        resource: '../../Security/*'

    SecurityBundle\Security\Loader\LoaderStub:
        public: true